export const COMMON_COPY = {
  brand: 'Expense Tracker',
  add: 'Add',
  edit: 'Edit',
  delete: 'Delete',
  update: 'Update',
  save: 'Save',
  cancel: 'Cancel',
  setDate: 'Set Date',
  actions: 'Actions',
  selectOne: 'Please select one',
  noChanges: 'No changes to save',
  // COMMON
  email: 'Email',
  emailPlaceholder: 'johndoe@email.com',
  password: 'Password',
  passwordPlaceHolder: 'abc123@!$',
  // REGISTER
  registerAccount: 'Register Account',
  firstName: 'First Name',
  firstNamePlaceholder: 'John',
  lastName: 'Last Name',
  lastNamePlaceholder: 'Doe',
  passwordRepeat: 'Repeat Password',
  register: 'Register',
  // LOGIN
  logIntoAccount: 'Log into account',
  login: 'Login',
  emailRequired: 'Email Required',
  passwordRequired: 'Password Required',
  firstNameRequired: 'First Name Required',
  lastNameRequired: 'Last Name Required',
  passwordMustMatch: 'Passwords must match',
  addAccount: 'Add Account',
  editAccount: 'Edit Account',
  accountName: 'Account Name',
  accountNamePlaceholder: 'Credit Card',
  initialAmount: 'Initial Amount',
  includeInBalance: 'Include in Balance',
  nameError: 'Name required',
  amountError: 'Amount cannot be zero or less',
  categoryError: 'Category required',
  accountError: 'Account required',
  accountTransferMatchError: 'Cannot transfer to the same account',
  added: 'Added',
  created: 'Created',
  updated: 'Updated',
  deleted: 'Deleted',
  addInitialAmount: 'Add initial amount',
  uniqueError: 'Values need to be unique',
  goals: 'Goals',
  addGoal: 'Add Goal',
  editGoal: 'Edit Goal',
  goalName: 'Goal Name',
  goalNamePlaceholder: 'Camera',
  targetDate: 'Target Date',
  goalPayment: 'Goal Payment',
  notGoal: 'Not a goal',
  saveDaily: 'Save Daily',
  saveWeekly: 'Save Weekly',
  saveMonthly: 'Save Monthly',
  currentAmount: 'Current Amount',
  TargetAmount: 'Target Amount',
  budgets: 'Budgets',
  addBudget: 'Add Budget',
  editBudget: 'Edit Budget',
  budgetName: 'Budget Name',
  budgetNamePlaceholder: 'Takeout',
  startDate: 'Start Date',
  endDate: 'End Date',
  accounts: 'Balance Accounts',
  otherAccounts: 'Other Accounts',
  goalAccounts: 'Goal Accounts',
}

export const TRANSACTION_COPY = {
  // COMMON
  name: 'Name',
  note: 'Note',
  account: 'Account',
  category: 'Category',
  amount: 'Amount',
  currency: 'Currency',
  date: 'Date',
  expense: 'Expense',
  nameRequired: 'Transaction name required',
  categoryRequired: 'Transaction category required',
  amountRequired: 'Transaction amount required',
  currencyRequired: 'Transaction currency required',
  transactionAdded: 'Transaction added',
  transactionUpdated: 'Transaction updated',
  transactionDeleted: 'Transaction deleted',
  // TRANSACTION LIST
  transactionType: 'Transaction Type',
  transactions: 'Transactions',
  // TRANSACTION FORM
  addTransaction: 'Add Transaction',
  editTransaction: 'Edit Transaction',
  namePlaceholder: 'Ice cream',
  notePlaceholder: 'Ice cream with John at Ice-Co',
  amountPlaceholder: '100',
  currencyPlaceholder: '$',
  // TRANSACTION CHARTS
  expensesVsIncomes: 'Expenses Vs Incomes',
  expensesForPeriod: 'Expenses for period',
  transactionsForPeriod: 'Transactions For Period',
  spendPerDay: 'Spend Per Day',
  spendPerWeek: 'Spend Per Week',
  balance: 'Balance',
  moneyIn: 'Money In',
  moneyOut: 'Money Out',
  fromAccount: 'From Account',
  toAccount: 'To Account',
  transfer: 'Transfer',
  deleted: 'Transaction Deleted',
  categoryUsage: 'Categories',
  noTransactions: 'No transactions to view',
}

export const CATEGORY_COPY = {
  categories: 'Categories',
  addCategory: 'Add Category',
  editCategory: 'Edit Category',
  category: 'Category',
  categoryPlaceholder: 'Gift',
  delete: 'Delete category',
  edit: 'Edit',
  categoryNameError: 'Category requires a name',
  name: 'Name',
  created: 'Category Created',
  updated: 'Category Updated',
  deleted: 'Category Deleted',
  expenseCategories: 'Expense Categories',
  incomeCategories: 'Income Categories',
  transferCategories: 'Transfer Categories',
  expenseUsage: 'Expense Usage',
  incomeUsage: 'Income Usage',
  transferUsage: 'Transfer Usage',
  icon: 'Icon',
}

export const NAVIGATION_COPY = {
  account: 'Account',
  login: 'Login',
  register: 'Register',
  logout: 'Logout',
}

export const SETTINGS_COPY = {
  settings: 'Settings',
  userSettings: 'User Settings',
  defaultCurrency: 'Default currency',
  defaultCurrencyPlaceholder: '$',
  save: 'Save',
}

export const DIALOG_COPY = {
  defaultWarning:
    'You are about to do something very important. Are you sure you want to continue?',
  yes: 'Yes',
  no: 'No',
  warning: 'Warning',
}
