export default {
  budgets: 'Budgets',
  addBudget: 'Add Budget',
  editBudget: 'Edit Budget',
  delete: 'Delete',
  edit: 'Edit',
  recreate: 'Recreate',
  startDate: 'Start Date',
  endDate: 'End Date',
  dailySpendLimit: 'Daily Spending Limit',
  weeklySpendLimit: 'Weekly Spending Limit',
  dailySpendAmount: 'Daily Spending Amount',
  weeklySpendAmount: 'Weekly Spending Amount',
  budgetName: 'Budget Name',
  budgetNamePlaceholder: 'Takeout',
  category: 'Category',
  amount: 'Amount',
  amountPlaceholder: '100',
  note: 'Note',
  notePlaceholder: 'Budget for takeout',
  complete: '(Complete)',
  spendingPeriod: 'Spending Period',
  daysRemaining: 'Days Remaining',
  balance: 'Current Balance',
  spendLimit: 'Spending Limit',
  adjustBalance: 'Adjust Balance',
}
