export default {
  categories: 'Categories',
  addCategory: 'Add Category',
  editCategory: 'Edit Category',
  category: 'Category',
  categoryPlaceholder: 'Gift',
  delete: 'Delete',
  edit: 'Edit',
  categoryNameError: 'Category requires a name',
  name: 'Name',
  created: 'Category Created',
  updated: 'Category Updated',
  deleted: 'Category Deleted',
  expenseCategories: 'Expense',
  incomeCategories: 'Income',
  transferCategories: 'Transfer',
  expenseUsage: 'Expense Usage',
  incomeUsage: 'Income Usage',
  transferUsage: 'Transfer Usage',
}
