export default {
  accountLogin: 'Log into Expense',
  accountRegister: 'Register account',
  emailPlaceholder: 'Email address',
  passwordPlaceHolder: 'Password',
  passwordRepeatPlaceHolder: 'Password Repeat',
  login: 'Login',
  emailRequired: 'Email Required',
  passwordRequired: 'Password Required',
  firstNameRequired: 'First Name Required',
  lastNameRequired: 'Last Name Required',
  passwordMustMatch: 'Passwords must match',
  registerAccount: 'Register Account',
  firstNamePlaceholder: 'First Name',
  lastNamePlaceholder: 'Last Name',
  passwordRepeat: 'Repeat Password',
  register: 'Register',
  noAccount: "Don't have an account?",
}
