export default {
  accountLogin: 'Account Login',
  accountRegister: 'Account Register',
  email: 'Email',
  emailPlaceholder: 'johndoe@email.com',
  password: 'Password',
  passwordPlaceHolder: 'abc123@!$',
  login: 'Login',
  emailRequired: 'Email Required',
  passwordRequired: 'Password Required',
  firstNameRequired: 'First Name Required',
  lastNameRequired: 'Last Name Required',
  passwordMustMatch: 'Passwords must match',
  registerAccount: 'Register Account',
  firstName: 'First Name',
  firstNamePlaceholder: 'John',
  lastName: 'Last Name',
  lastNamePlaceholder: 'Doe',
  passwordRepeat: 'Repeat Password',
  register: 'Register',
}
