export default {
  accountLogin: 'Log into Expense',
  accountRegister: 'Register account',
  email: 'Email address',
  emailPlaceholder: 'johndoe@email.com',
  password: 'Password',
  passwordPlaceHolder: '@abc123def',
  passwordRepeat: 'Password Repeat',
  login: 'Login',
  emailRequired: 'Email Required',
  passwordRequired: 'Password Required',
  firstNameRequired: 'First Name Required',
  lastNameRequired: 'Last Name Required',
  passwordMustMatch: 'Passwords must match',
  registerAccount: 'Register Account',
  firstName: 'First Name',
  firstNamePlaceholder: 'John',
  lastName: 'Last Name',
  lastNamePlaceholder: 'Doe',
  register: 'Register',
  noAccount: "Don't have an account?",
}
