export default {
  transactions: 'Transactions',
  addTransaction: 'Add Transaction',
  editTransaction: 'Edit Transaction',
  created: 'Transaction Created',
  deleted: 'Transaction Deleted',
  delete: 'Delete transaction',
  updated: 'Transaction Updated',
  transfer: 'Transfer',
  balance: 'Balance',
  income: 'Income',
  expense: 'Expense',
  spendPerDay: 'Daily Spending',
  spendPerWeek: 'Weekly Spending',
  account: 'Account',
  category: 'Category',
  fromAccount: 'From Account',
  toAccount: 'To Account',
  name: 'Name',
  namePlaceholder: 'Dinner',
  amount: 'Amount',
  amountPlaceholder: '100',
  date: 'Date',
  note: 'Note',
  notePlaceholder: 'Meat, Vegetable and Milk from FoodStop',
  accountNameError: 'Transaction Name Required',
  accountError: 'Account Required',
  accountTransferMatchError: 'Cannot Transfer to the same account',
}
